config/routes.rb
Rails.application.routes.draw do
  root to: "apps#index"
  get "/auth/:provider/callback" => "sessions#create"
  get "/auth/failure" => "sessions#failure"
  get '/login' => 'sessions#new', :as => :login
  get '/logout' => 'sessions#destroy', :as => :logout

  resources :apps, only: [:index]


  resources :subdomains
end

app/models/dnsimple_client.rb
class DNSimpleClient
  attr_reader :email, :token

  def initialize(email, token)
    @email = email
    @token = token
  end

  def register_subdomain(subdomain, content)
    #post to dnsimple; return dnsimple record id or error
  end

  def records
    #return all records for given thing
  end

  def http_client
    @http_client ||= Faraday.new(url: "https://api.dnsimple.com") do |conn|
                       conn.headers["X-DNSimple-Token"] = "#{email}:#{token}"
                       conn.headers["Accept"] = "application/json"
                     end
  end
end

app/models/subdomain.rb
class Subdomain < ActiveRecord::Base
  validates :subdomain, presence: true, uniqueness: true
  validates :content, presence: true
  validates :dnsimple_record_id, presence: true, uniqueness: true
  validates :user_github_id, presence: true
  #belongs_to :user

  def register!
    begin
      record = DNSIMPLE.domains.create_record("turingapps.io",
                                              record_type: "CNAME",
                                              name: subdomain,
                                              content: content)
      if record && record.is_a?(Dnsimple::Struct::Record)
        self.dnsimple_record_id = record.id
      end
      save
    rescue Dnsimple::RequestError, ArgumentError
      errors.add(:subdomain, "sorry, couldn't register this subdomain with DNSimple. It may already be taken")
      false
    end
  end

  def deregister!
    Rails.logger.info("Going to de-register subdomain #{subdomain}.turingapps.io (DNSimple #{dnsimple_record_id})")
    begin
      response = DNSIMPLE.domains.delete_record("turingapps.io", dnsimple_record_id)
      if response.success?
        Rails.logger.info("DNSimple deregistration succeeded; will delete Subdomain db record")
        destroy
      else
        raise Dnsimple::RequestError.new(resp)
      end
      true
    rescue Dnsimple::RequestError, Dnsimple::NotFoundError => ex
      Rails.logger.info("DNSimple deregistration failed for #{subdomain}.turingapps.io (DNSimple record #{dnsimple_record_id}): #{ex}")
      false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include TuringAuth::CurrentUser
  protect_from_forgery with: :exception

  def require_login
    redirect_to login_path unless current_user
  end
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  def index
    @apps = Subdomain.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if current_user
      redirect_to subdomains_path
    else
      redirect_to '/auth/github'
    end
  end

  def create
    auth = request.env["omniauth.auth"]
    user_info = {github_id: auth.uid, github_token: auth.credentials.token,
                 github_name: auth.info.nickname, email: auth.info.email}
    user = TuringAuth::User.new(user_info)
    if user.valid? && user.turing_member?
      @current_user = user
      session[:current_user] = @current_user.as_json
      redirect_to subdomains_path
    else
      flash[:error] = "Sorry, only members of the Turing github organization can do that."
      redirect_to root_path
    end
  end

  def failure
    Rails.logger.error("Oauth failed...#{params[:message]}")
    flash[:notice] = params[:message]
    redirect_to root_path
  end

  def destroy
    session[:current_user] = nil
    redirect_to root_path
  end
end

app/controllers/subdomains_controller.rb
class SubdomainsController < ApplicationController
  before_filter :require_login
  before_filter :load_subdomain, only: [:destroy, :show, :edit, :update]
  before_filter :require_owner, only: [:destroy, :edit, :update]
  def index
  end

  def new
    @subdomain = current_user.subdomains.new
  end

  def create
    @subdomain = Subdomain.new(subdomain_params)
    if @subdomain.register!
      #TODO: need to add step to tell user to configure their heroku stuff
      flash[:message] = "Congrats, you registered the subdomain #{@subdomain.subdomain}.turingapps.io to point to #{@subdomain.content}"
      redirect_to subdomains_path
    else
      flash[:error] = "sorry, there was an issue registering your subdomain"
      render :new
    end
  end

  def destroy
    if @subdomain.deregister!
      flash[:success] = "Unregistered subdomain #{@subdomain.subdomain}.turingapps.io"
    else
      flash[:error] = "Whoops, we couldn't de-register that subdomain."
    end
    redirect_to subdomains_path
  end

  private

  def require_owner
    unless current_user && @subdomain.user_github_id == current_user.github_id
      flash[:error] = "You can't do that..."
      redirect_to subdomains_path
    end
  end

  def load_subdomain
    @subdomain = Subdomain.find(params[:id])
  end

  def subdomain_params
    params.require(:subdomain).permit(:content, :subdomain).merge(user_github_id: current_user.github_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/apps/index.html.erb
<h1>Welcome to turingapps.io!</h1>
<h2>This site houses a collection of applications produced by students at the Turing School of Software and Design</h2>
<h2>Browse some of the work below:</h2>


<ul>
<% @apps.each do |app| %>
  <li><%= link_to app.subdomain, "http://#{app.subdomain}.turingapps.io" %></li>
<% end %>
</ul>

<p><%= link_to "sign in to add a new app", login_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Namer</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :class => "flash_#{name}" %>
  <% end %>
<% end %>

<% if current_user %>
  <p>hi, <%= current_user.github_name %></p>
  <p><%= link_to "logout", logout_path %></p>
<% else %>
  <p><%= link_to "login", login_path %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/subdomains/_form.html.erb
<%= form_for @subdomain do |f| %>
  <%= f.label :content %>:
  <%= f.text_field :content %><span> (original URL or IP Address) </span><br />

  <%= f.label :subdomain %>:
  <%= f.text_field :subdomain %><span>(.turingapps.io)</span><br />

  <%= f.submit %>
<% end %>

app/views/subdomains/index.html.erb
<h2>Here are the subdomains registered for GH user <%= current_user.github_name %> (<%= current_user.github_id %>):</h2>

<% current_user.subdomains.each do |s| %>
  <p><%= s.subdomain %> <span><%= link_to "delete subdomain", subdomain_path(s), method: "delete" %></span></p>
<% end %>

<div>
  <p><%= link_to "Register a new subdomain", new_subdomain_path %></p>
</div>

app/views/subdomains/new.html.erb
<h2>Register a new Subdomain</h2>

<%= render partial: "subdomains/form", subdomain: @subdomain %>